version: "3.8"
services:
  postgres_db:
    image: postgres:latest
    container_name: shareplate_db
    environment:
      - POSTGRES_USER=shareadmin
      - POSTGRES_PASSWORD=sharepass
      - POSTGRES_DB=shareplate_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata:
